# Generated by Django 5.2.12 on 2026-04-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_rasm_izoh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='izoh',
            options={'ordering': ['-yaratilgan']},
        ),
        migrations.AlterField(
            model_name='izoh',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='blog.post'),
        ),
    ]
