# Generated by Django 5.2.12 on 2026-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_izoh_options_alter_izoh_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='muallif',
            field=models.CharField(max_length=100),
        ),
    ]
