# Generated by Django 5.2.12 on 2026-04-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_post_and_izoh_authors(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Post = apps.get_model('blog', 'Post')
    Izoh = apps.get_model('blog', 'Izoh')

    def ensure_user(name, fallback_prefix):
        if not name:
            return None
        existing = User.objects.filter(username=name).first()
        if existing:
            return existing

        username = name.strip().lower().replace(' ', '_')
        if not username:
            username = f'{fallback_prefix}_{name}'
        original_username = username
        suffix = 1
        while User.objects.filter(username=username).exists():
            username = f'{original_username}_{suffix}'
            suffix += 1

        user = User.objects.create(username=username)
        user.password = ''
        user.save()
        return user

    for post in Post.objects.all():
        author_name = getattr(post, 'muallif', None)
        if not author_name:
            continue

        if isinstance(author_name, int):
            continue

        user = ensure_user(author_name, f'post_{post.pk}')
        if user:
            post.muallif = str(user.id)
            post.save()

    for izoh in Izoh.objects.all():
        author_name = getattr(izoh, 'ism', None)
        if not author_name:
            continue

        user = ensure_user(author_name, f'izoh_{izoh.pk}')
        if user:
            izoh.muallif_id = user.id
            izoh.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_muallif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-yaratilgan_sana']},
        ),
        migrations.AddField(
            model_name='izoh',
            name='muallif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_post_and_izoh_authors),
        migrations.RemoveField(
            model_name='izoh',
            name='ism',
        ),
        migrations.AlterField(
            model_name='post',
            name='muallif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='kategoriya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postlar', to='blog.kategoriya'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
