# Generated by Django 5.2.12 on 2026-04-05 13:48

import blog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cover_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='postlar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='profillar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='PostRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='post_rasmlari/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='blog.post')),
            ],
        ),
    ]
