# Generated by Django 5.2.12 on 2026-04-09 16:57

import blog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_sarlavha_alter_post_yaratilgan_sana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrasm',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='izoh',
            options={'ordering': ['-yaratilgan_sana']},
        ),
        migrations.AlterModelOptions(
            name='kategoriya',
            options={},
        ),
        migrations.RenameField(
            model_name='izoh',
            old_name='yaratilgan',
            new_name='yaratilgan_sana',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='foydalanuvchi',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reel',
            old_name='created_at',
            new_name='yaratilgan_vaqt',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='kategoriya',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='cover_rasm',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tugilgan_sana',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='ism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='nom',
            field=models.CharField(default='Eski reel', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='izoh',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='korildi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='profil_rasmlari/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(upload_to='reels/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv'])]),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_like'),
        ),
        migrations.DeleteModel(
            name='PostRasm',
        ),
    ]
