# Generated by Django 5.2.12 on 2026-04-09 17:51

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_postrasm_post_alter_izoh_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cover_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='profillar/cover/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), blog.models.validate_file_size]),
        ),
    ]
